version: "3"

services:

  fastapi:
    image: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_pass.conf:/mosquitto/config/mosquitto_pass.conf
    environment:
      - MOSQUITTO_USERNAME=sensor_user
      - MOSQUITTO_PASSWORD=sensor123
    