version: "1"

services:

  fastapi:
    image: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    